@startuml uc1_signUp

left to right direction

actor ": Usuario" as user

entity ": Member" as mod
boundary ": SignUpFrame" as vis
control ": SignUpController" as con

vis --> user : 1: Mostrar pantalla de Registro
user --> con : 2: Envia datos de registro
con --> mod : 3: Validar / Registrar datos
con --> vis : 4: Solicitar Pantalla indice
vis --> user : 5: Mostrar Pantalla índice

@enduml
