@startuml uc1_signUp

left to right direction

actor ": User" as user

entity ": Member" as mod
boundary ": SignUpFrame" as vis
boundary ": MainFrame" as main
control ": SignUpController" as con

user --> con : 1: requestSignUp()
con --> vis : 2: requestDisplay (Frame signUpFrame)
vis --> user : 3: showFrame (Frame signUpFrame)
user --> con : 4: sendNewUserData (Member user)
con --> mod : 5: askNewUserValidation (Member User)
mod --> mod : 6: validateData (Member user) / registerData (Member user)
mod --> con : 7: reportNewUser() 
con --> main : 8: askDisplay (Frame mainFrame)
main --> user : 9: showFrame (Frame mainFrame)

@enduml
