@startuml uc2_login

left to right direction

actor ": User" as user
boundary ": SignInFrame" as vis
entity ": Member" as mod
control ": SignInController" as con

note right of con
    5.1 es un flujo alterno, 
    si los datos son rechazados
end note

vis --> user : 1: Mostrar pantalla de inicio
user --> con : 2: Solicitar Iniciar Sesión
con --> mod : 3: Comprobar existencia de datos del Usuario 
mod --> con : 4: Resultado de validación de datos 
con --> vis : 5: Enviar Pantalla principal
con --> vis : 5.1: Enviar Pantalla SignUp
vis --> user : 6: Mostrar Pantalla resultante

@enduml