@startuml uc2_login

left to right direction

actor ": User" as user
entity ": Member" as mod
control ": SignInController" as con
boundary ": SignInFrame" as vis
boundary ": MainFrame" as main
boundary ": SignUpFrame" as sup

note right of con
    7.2 es un flujo alterno, 
    si los datos son rechazados
end note

note right of sup 
    8.2 es la pantalla en
    caso de rechazo
end note


user --> vis : 1: requestLogIn()
vis --> user : 2: showFrame (Frame signInFrame)
user --> con : 3: sendUserData(String username, String password)
con --> mod : 4: askUserValidation(Member user)
mod --> mod : 5: authUserData(Member user) 
mod --> con : 6: sendValidationStatus() 
con --> main : 7.1: askDisplay (Frame mainFrame)
con --> sup : 7.2: askDisplay (Frame signUpFrame)
main --> user : 8.1: showFrame (Frame mainFrame)
sup --> user : 8.2: showFrame (Frame signUpFrame)

@enduml