@startuml uc3_createPublication

left to right direction

actor ": User" as user

entity ": PublicationApprover" as mod
boundary ": newPublicationFrame" as vis
boundary ": MainFrame" as main
control ": PublicationController" as con

note right of con
    8.1 Es una acción en 
    caso de que se rechace 
    la publicación 
end note

user --> con : 1: requestCreatePublication()
con --> vis : 2: askDisplay (Frame newPublicationFrame)
vis --> user : 3: showFrame (Frame newPublicationFrame)
user --> con : 4: newPublication (Publicacion newPub)
con --> mod : 5: askValidatePublication (Publicacion newPub)
mod --> mod : 6: validatePublication (Publicacion newPub)
mod --> con : 7: reportPublicationStatus()
con --> vis : 8: askDisplay (Frame newPublicationFrame, PopUp approved)
con --> vis : 8.1: askDisplay (Frame newPublicationFrame, PopUp rejected)
vis --> user : 9: showFrame (Frame newPublicationFrame, PopUp approved)
con -up-> main : 10: askDisplay (Frame mainFrame)
main --> user : 11: showFrame (Frame mainFrame)

@enduml