@startuml uc3_createPublication

left to right direction

actor ": User" as user

entity ": PublicationApprover" as mod
boundary ": NewPublicationFrame" as vis
boundary ": MainFrame" as main
control ": PublicationController" as con

note right of con
    7.1 Es una acción en 
    caso de que se rechace 
    la publicación 
end note

user --> vis : 1: requestCreatePublication()
vis --> user : 2: showFrame (Frame newPublicationFrame)
user --> con : 3: newPublication (Publicacion newPub)
con --> mod : 4: askValidatePublication (Publicacion newPub)
mod --> mod : 5: validatePublication (Publicacion newPub)
mod --> con : 6: reportPublicationStatus()
con --> vis : 7: askDisplay (Frame newPublicationFrame, PopUp approved)
con --> vis : 7.1: askDisplay (Frame newPublicationFrame, PopUp rejected)
vis --> user : 8: showFrame (Frame newPublicationFrame, PopUp approved)
con -up-> main : 9: askDisplay (Frame mainFrame)
main --> user : 10: showFrame (Frame mainFrame)

@enduml