@startuml uc3_createPublication

left to right direction

actor ": User" as user

entity ": PublicationApprover" as mod
entity ": PublicationWarehouse" as pw
boundary ": CreatePubFrame" as vis
control ": PublicationController" as con

note right of con
    6.1 Es una acción en 
    caso de que se rechace 
    la publicación 
end note

vis --> user : 1: Mostrar pantalla Crear Publicación
user --> con : 2: Enviar datos de publicación creada
con --> mod : 3: Solicita aprobación de la publicación
mod --> con : 4: Envía respuesta (Aprobada / Rechazada)
con --> pw : 5: Envia publicacion a cargar en base de datos
con --> vis : 6: Envía pantalla con Mensaje "Publicación Aprobada"
con --> vis : 6.1: Envía pantalla con Mensaje "Publicación Rechazada"
vis --> user : 7: Muestra pantalla con mensaje correspondiente
Vis --> user : 8: Muestra pantalla Principal

@enduml