@startuml uc4_createEvent

left to right direction

actor ": Docente / Colaborador" as user
boundary ": UI" as vis
entity ": Base de datos" as mod
control ": Sistema" as con

user --> con : 1: Selecciona la pestaña calendario
con --> mod : 2: Procesa la orden
mod --> con : 3: Carga los datos del calendario
con --> vis : 4: Da acceso a la pantalla de calendario
vis --> user : 5: Muestra pantalla de calendario junto a eventos disponibles
user --> con : 6: Selecciona la opción de crear evento
con --> mod : 7: Solicita acceder a contenido para crear evento
mod --> vis : 8: Da acceso a datos
vis --> user : 9: Muestra pantalla de creación de evento
user --> con : 10: Inserta datos del evento
con --> mod : 11: Envía datos
mod --> con : 12: Verifica datos
con --> vis : 13: confirma el evento
vis --> user : 14: Muestra pantalla de calendario con evento creado

@enduml