@startuml uc4_createEvent

left to right direction

actor ": User" as user
boundary ": NewEventFrame" as vis
boundary ": MainFrame" as main
entity ": EventApprover" as mod
entity ": Calendar" as cal
control ": NewEventController" as con

user --> con : 1: requestNewEvent()
con --> vis : 2: askDisplay (Frame newEventFrame)
vis --> user : 3: showFrame (Frame newEventFrame)
user --> con : 4: newEvent (Event event)
con --> mod : 5: askValidateUser (Member user)
mod --> mod : 6: validateUserPermissions(Member user) / 7: validateEventData(Event event)
mod --> con : 7: reportValidation()
con --> cal : 8: askUpdateCalendar(Event event)
cal --> cal : 9: addEventToCalendar(Event event)
cal --> con : 10: reportCalendarUpdate()
con --> vis : 11: askDisplay (Frame newEventFrame, PopUp approved)
con --> vis : 11.1: askDisplay (Frame newEventFrame, PopUp rejected)
vis --> user : 12: showFrame (Frame newEventFrame, PopUp approved)
con -up-> main : 13: askDisplay (Frame mainFrame)
main --> user : 14: showFrame (Frame mainFrame)

@enduml