@startuml uc4_createEvent

left to right direction

actor ": User" as user
boundary ": CreateEventFrame" as vis
entity ": Profesor" as mod
entity ": EventApprover" as ea
entity ": Calendar" as cal
control ": newEventController" as con

vis --> user : 1: Muestra al usuario la pantalla Crear Evento
user --> con : 2: Envía los datos del evento
con --> mod : 3: Solicita comprobar si el usuario es profesor
mod --> con : 4: Dar respuesta y acceso
con --> ea : 5: Solicita si el evento cumple las condiciones para aprovar
ea --> con : 6: Aprueba las condiciones
con --> cal : 7: Solicitar disponibilidad y agregación de evento
cal --> con : 8: Comunicar estatus de evento
con --> vis : 9: Envíar pantalla con Pop-up
vis --> user : 10: Mostrar pantalla con mensaje de evento (Aprobado/Rechazado)
vis --> user : 11: Mostrar pantalla principal

@enduml