@startuml uc5_createEvent

left to right direction

actor ": User" as user
boundary ": NewEventFrame" as vis
boundary ": MainFrame" as main
entity ": EventApprover" as mod
entity ": Calendar" as cal
control ": NewEventController" as con

user --> vis : 1: requestNewEvent()
vis --> user : 2: showFrame (Frame newEventFrame)
user --> vis : 3: newEvent (Event event)
vis --> con : 4: sendInputData (Event event)
user --> con : 5: newEvent (Event event)
con --> mod : 6: askValidateUser (Member user)
mod --> mod : 7: validateUserPermissions(Member user) / 8: validateEventData(Event event)
mod --> con : 9: reportValidation()
con --> cal : 10: askUpdateCalendar(Event event)
cal --> cal : 11: addEventToCalendar(Event event)
cal --> con : 12: reportCalendarUpdate()
con --> vis : 13: askDisplay (Frame newEventFrame, PopUp approved)
con --> vis : 13.1: askDisplay (Frame newEventFrame, PopUp rejected)
vis --> user : 14: showFrame (Frame newEventFrame, PopUp approved)
con -up-> main : 15: askDisplay (Frame mainFrame)
main --> user : 16: showFrame (Frame mainFrame)

@enduml