@startuml DiagrmaDeEstados_FacUpdate

[*] --> Iniciando_Sesion

state c1 <<choice>>
Iniciando_Sesion --> c1

c1 --> Haciendo_SignUp : [Usuario no existe]
state c2 <<choice>>
Haciendo_SignUp --> c2
c2 --> Haciendo_Login : [Pertenece a la Facultad]
Haciendo_Login --> Navegando_en_App
c2 --> [*] : [No pertenece a la Facultad]

c1 --> Haciendo_Login : [Usuario Existe]

state Navegando_en_App {
    [*] -down-> Decidiendo_Accion
    
    state Gestionando_Publicaciones {
        state c3 <<choice>>
        [*] --> c3
        c3 --> Subiendo_Publicacion : [Moderador Aprobó]
        c3 --> Rechazando_Publicacion : [Moderador Desaprobó]
    }
    
    state Gestionando_Eventos {
        state c4 <<choice>>
        [*] --> c4
        c4 -down-> Creando_Evento : [Puede crear]
        c4 -down-> Suscribiendo_A_Evento : [No Puede crear]
    }
    

    Decidiendo_Accion --> Gestionando_Publicaciones
    Decidiendo_Accion --> Revisando_Notificaciones
    Decidiendo_Accion --> Revisando_Publicaciones
    Decidiendo_Accion --> Revisando_Calendario
    Decidiendo_Accion --> Gestionando_Eventos
    Decidiendo_Accion --> Cerrando_Sesion: Cerrar Sesión
    
    Gestionando_Eventos -up-> Decidiendo_Accion
    Gestionando_Publicaciones -up-> Decidiendo_Accion
    Revisando_Notificaciones -up-> Decidiendo_Accion
    Revisando_Publicaciones -up-> Decidiendo_Accion
    Revisando_Calendario -up-> Decidiendo_Accion
}

Cerrando_Sesion --> [*]
Navegando_en_App --> [*] : Cerrar Sesión

@enduml