package View;

import Controller.Publications.PublicationController;
import Controller.session.SesionController;
import Model.Comment;
import Model.Publication;
import Model.User;
import java.awt.BorderLayout;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Josue Guedez
 */
public class comentView extends javax.swing.JFrame {
    
    
    private SesionController SC;
    private Publication actualData;
    private PublicationController PC;

    /**
     * Creates new form comentView
     */
    public comentView() {
        initComponents();
        SC = SesionController.GetInstance();
        PC = PublicationController.GetInstance();
    }

  
    public void addComment(String username, String comment) {
        JPanel commentPanel = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 5, 5, 5);
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;

        JLabel userLabel = new JLabel(username);
        userLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        commentPanel.add(userLabel, gbc);

        gbc.gridy++;
        JLabel commentLabel = new JLabel("<html>" + comment + "</html>");
        commentLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 12));
        commentPanel.add(commentLabel, gbc);

        CommentsPane.add(commentPanel);
        CommentsPane.revalidate();
        
    }
    
    private void setComments(List<Comment> comments){
        
        String texto = "";
        for(Comment c : comments){
            User us = SC.SearchUserByID(c.getAutorID());
            String name;
            if(us == null)name = "Usuario Anonimo";
            else{name = us.userName;}
            String text = c.getText();
            texto += name + "\n";
            texto += text + "\n\n";
        }
        
        CommentsPane.setText(texto);
        
    }
    
    public void setPublication(Publication p){
        actualData = p;
        setComments(actualData.getComments());
    }
    private void addComment(String Text){
        Comment com = new Comment();
        com.setAutorID(SC.ActualSession.ID);
        com.setText(Text);
        PC.AddComment(actualData.getPUBLICATION_ID(), com);
        setPublication(PC.searchPublication(actualData.getPUBLICATION_ID()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        NewCommentText = new javax.swing.JTextArea();
        ComentButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        CommentsPane = new javax.swing.JTextPane();
        noCommentsLabel = new javax.swing.JLabel();

        noCommentsLabel.setVisible(false);
        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Comentarios");

        NewCommentText.setColumns(20);
        NewCommentText.setRows(5);
        jScrollPane1.setViewportView(NewCommentText);

        ComentButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ComentButton.setForeground(new java.awt.Color(204, 0, 0));
        ComentButton.setText("Comentar");
        ComentButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 0, 0), 2, true));
        ComentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComentButtonActionPerformed(evt);
            }
        });

        CommentsPane.setEditable(false);
        if(CommentsPane.getText().equals("")){
            noCommentsLabel.setVisible(true);
        }
        jScrollPane2.setViewportView(CommentsPane);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ComentButton, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(ComentButton, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addContainerGap(295, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(96, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        noCommentsLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        noCommentsLabel.setForeground(new java.awt.Color(102, 102, 102));
        noCommentsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noCommentsLabel.setText("NO HAY COMENTARIOS");
        noCommentsLabel.setToolTipText("NO HAY COMENTARIOS");
        noCommentsLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(noCommentsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(25, 25, 25)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(175, 175, 175)
                    .addComponent(noCommentsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(176, 176, 176)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComentButtonActionPerformed
        String t = NewCommentText.getText();
        addComment(t);
        NewCommentText.setText("");
    }//GEN-LAST:event_ComentButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(comentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(comentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(comentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(comentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                comentView view = new comentView();
                view.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ComentButton;
    private javax.swing.JTextPane CommentsPane;
    private javax.swing.JTextArea NewCommentText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel noCommentsLabel;
    // End of variables declaration//GEN-END:variables
}
