@startuml uc1_signUp

left to right direction

actor ": User" as user

entity ": Member" as mod
boundary ": SignUpFrame" as vis
boundary ": MainFrame" as main
control ": SignUpController" as con

user --> vis 
vis --> user 
user --> vis 
vis --> con
con --> mod 
mod --> mod 
mod --> con
con --> main
main --> user

@enduml
