@startuml uc2_login

left to right direction

actor ": User" as user
entity ": Member" as mod
control ": SignInController" as con
boundary ": SignInFrame" as vis
boundary ": MainFrame" as main
boundary ": SignUpFrame" as sup

note right of con
    Flujo alterno, 
    si los datos son rechazados
end note

note right of sup 
    Pantalla en
    caso de rechazo
end note

user --> vis
vis --> user 
user --> vis 
vis --> con
con --> mod 
mod --> mod 
mod --> con 
con --> main 
con --> sup 
main --> user 
sup --> user

@enduml