@startuml uc3_createPublication

left to right direction

actor ": User" as user

entity ": PublicationApprover" as mod
boundary ": NewPublicationFrame" as vis
boundary ": MainFrame" as main
control ": PublicationController" as con

user --> vis
vis --> user 
user --> vis
vis --> con 
con --> mod
mod --> mod
mod --> con 
con --> vis 
con --> vis 
vis --> user
con -up-> main 
main --> user

@enduml