@startuml uc3_createPublication

left to right direction

actor ": Usuario" as user

entity ": Base de datos" as mod
boundary ": UI" as vis
control ": Sistema" as con

vis --> user
user --> con
con --> mod
mod --> vis 
mod --> con 
con --> vis 
user --> vis

@enduml