@startuml uc4_createEvent

left to right direction

actor ": User" as user
boundary ": NewEventFrame" as vis
boundary ": MainFrame" as main
entity ": EventApprover" as mod
entity ": Calendar" as cal
control ": NewEventController" as con

user --> vis
vis --> user 
user --> vis 
vis --> con 
user --> con 
con --> mod
mod --> mod
mod --> con
con --> cal
cal --> cal
cal --> con 
con --> vis
con --> vis 
vis --> user
con -up-> main
main --> user 

@enduml