@startuml uc4_createEvent

left to right direction

actor ": Docente / Colaborador" as user
boundary ": UI" as vis
entity ": Base de datos" as mod
control ": Sistema" as con

user --> con
con --> mod 
mod --> con 
con --> vis 
vis --> user
mod --> vis

@enduml