@startuml mainUC_classDiagram

skinparam ClassFontSize 15
skinparam ClassBorderThickness 2

class "User" as user {
    -name: String
    -lastName: String
    -username: String
    -password: String
    -major: String
    -isModerator: Boolean

    +signUp()
    +logIn()
    +createPublication()
    +createEvent()
    +viewCalendar()
}

class "Publication" as pub {    
    -image: Image
    -uploadDate: Date
    -description: String
    -publicationOwner: User
    -comments: List<Comment>
    +addComment(comment: Comment)
    +removeComment(comment: Comment)
}



class "Event" as eve {
    -uploadDate: Date
    -description: String
    -eventDate: Date
    -interestGroup: String
    -eventPlace: String

    +addToCalendar(calendar: Calendar)
}

class "Moderator" as mod {
    +checkUserInDB(username: String, password: String): Boolean
    +approveLogIn(username: String, token: String): Boolean
    +approvePublication(publication: Publication)
    +approveEvent(event: Event)
}

class "Calendar" as cal {
    -events: List<Event>

    +addEvent(event: Event)
    +removeEvent(event: Event)
    +getEvents(): List<Event>
}

user <|-- mod
user "0..*" -right- cal : views >
mod "1..*" -- "1..*" eve : approves >
mod "1..*" -- "1..*" pub : approves >
pub o-- "0..*" eve : references >
user "0..*" -- "0..*" pub : creates >
user "0..*" -- "0..*" eve : creates >
cal o-- "0..*" eve : contains >

@enduml
