@startuml package_diagram

skinparam FontSize 14
skinparam PackageBorderThickness 2

package "facupdate.entity" as model {
    class Member
    class EventApprover
    class Calendar
    class PublicationApprover
}

package "facupdate.view" as frame {
    class SignUpFrame
    class SignInFrame
    class MainFrame
    class NewPublicationFrame
    class NewEventFrame
}

package "facupdate.controller" as control {
    class SignUpController
    class SignInController
    class PublicationController
    class NewEventController
}

Member -- EventApprover
EventApprover -- Calendar
Member -- PublicationApprover

SignInFrame -- MainFrame
SignInFrame -- SignUpFrame
SignUpFrame -- MainFrame
MainFrame -- NewPublicationFrame
MainFrame -- NewEventFrame

frame --> control : > send user actions
control -up-> model : > request validation and exchange data 
model --> control : > send requests responses

@enduml
