@startuml uc1_signUp

left to right direction

actor ": Usuario" as user

entity ": Base de datos" as mod
boundary ": UI" as vis
control ": Sistema" as con

vis --> user
user --> con
con --> vis
con --> user
con --> mod
mod --> con 


@enduml
