@startuml diagramaUC1
skinparam classAttributeIconSize 0
skinparam ClassBorderThickness 2

class "InterfazRegistro" <<interface>>
class "FormularioRegistro" <<interface>>
class "ControladorRegistro" <<control>>
class "Integrante" <<entity>>
class "Perfil" <<interface>>

InterfazRegistro -- FormularioRegistro : displayForm
FormularioRegistro -- ControladorRegistro : sendForm
ControladorRegistro -- Integrante : addUserToDB
ControladorRegistro -- Perfil : displayProfile
@enduml