@startuml diagramaUC2
skinparam classAttributeIconSize 0
skinparam ClassBorderThickness 2

class "InterfazLogin" <<interface>>
class "FormularioLogin" <<interface>>
class "ControladorAutenticacion" <<control>>
class "Integrante" <<entity>>
class "SesionIntegrante" <<entity>>

InterfazLogin -- FormularioLogin : displayForm
FormularioLogin -- ControladorAutenticacion : sendForm
ControladorAutenticacion -- Integrante : authenticateUser
ControladorAutenticacion -- SesionIntegrante : open_or_reject
@enduml