@startuml uc2_login

left to right direction

actor ": Usuario" as user
boundary ": UI" as vis
entity ": Base de datos" as mod
control ": Sistema" as con

vis --> user
con --> user
user --> con
con --> mod 
mod --> con 
con --> vis 


@enduml